# Generated by Django 4.2.1 on 2023-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_cart_print_created_at_print_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='quantity',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
